n1 = int(input('numero 1: '))
n2 = int(input('numero 2: '))
n3 = input('digite algo: ')
n4 = input('digite algo: ')
n5 = input('digite algo: ')
soma = n1 + n2
print('{} + {} = {}'.format(n1,n2,soma))
print(n3.isnumeric())
print(n4.isalpha())
print(n5.isalnum())
