frase = 'Curso em video'
print(frase)
print(frase[9])
print(frase[9:13])
print(frase[9:21:2])
print(frase[9::3])
print(frase[:5])
print(frase[5:])
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('e'))
print('curso' in frase)
print(frase.replace('Python', 'android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.split())
